### ISSUE TITLE
Crash in v1.0.1 release build 

### ISSUE THREAD

**Issue by kylesmithapptegy** [StonlyHQ/stonly-android-sdk#3]
```
     Fatal Exception: java.lang.ClassCastException:
       at com.stonly.stonly.utils.helper.SafeAreaHelper.bottomAreaHeight(SafeAreaHelper.java:32)
       at com.stonly.stonly.utils.helper.SafeAreaHelper.getSafeAreaBottom(SafeAreaHelper.java:18)
       at com.stonly.stonly.trigger.TriggerManager.getTriggerViewGroup(TriggerManager.kt:114)
       at com.stonly.stonly.trigger.TriggerManager.clearView(TriggerManager.kt:358)
       at com.stonly.stonly.trigger.TriggerManager.clearFragment(TriggerManager.kt:351)
       at com.stonly.stonly.Stonly$listenerEventManager$1.onFragmentPaused(Stonly.java:220)
       at com.stonly.stonly.event.EventManager$eventListener$1.onFragmentPaused(EventManager.java:33)
       at com.stonly.stonly.event.StonlyFragmentLifecycleCallbacksAdapter.onFragmentPaused(StonlyFragmentLifecycleCallbacksAdapter.kt:33)
       at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentPaused(FragmentLifecycleCallbacksDispatcher.java:222)
       at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentPaused(FragmentLifecycleCallbacksDispatcher.java:218)
       at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:673)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:304)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by awlodarczyk** [comment]
fixed
